apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Common resources shared between environments
resources:
  - deployment/print-service-deploy.yaml
  - service/print-service-svc.yaml
  - autoscaling/print-service-autoscaler.yaml
